- name: Download/Install host-sflow package for Ubuntu
  apt:
    deb: "https://github.com/sflow/host-sflow/releases/download/v{{ hsflow_version }}/hsflowd_{{ hsflow_version }}_amd64.deb"
  when: ansible_distribution == "Ubuntu"

- name: Install hsflowd package for CentOS
  yum:
    name: https://github.com/sflow/host-sflow/releases/download/v2.0.7/hsflowd-centos7-2.0.7-1.x86_64.rpm
    state: present
  when: ansible_distribution == "CentOS"

- name: Create configuration fragments folder
  file:
    path: "{{ hsflow_conf_dir }}"
    state: directory

- set_fact:
    net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"

- name: Template config fragments
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ hsflow_conf_dir }}/{{ item.order|default('50') }}-{{ item.name }}.fragment"
  with_items:
    - { name: 'header', order: '00' }
    - { name: 'collector' }
    - { name: 'footer', order: '90' }

- name: Enable hsflowd at boot
  service:
    name: hsflowd
    enabled: yes
