- include: install.yml

- include: kvm.yml
  when: kvm|default(false)

- name: Assemble hsflowd.conf
  assemble:
    src: "{{ hsflow_conf_dir }}"
    dest: /etc/hsflowd.conf
    regexp: '\\.fragment$'
    delimiter: ' '
  notify: restart hsflowd
