- include: install.yml
  when: deploy_mode == 'install'

- include: hv.yml
  when: deploy_mode == 'hv'

- name: Assemble hsflowd.conf
  assemble:
    src: "{{ hsflow_conf_dir }}"
    dest: /etc/hsflowd.conf
    regexp: '\\.fragment$'
    delimiter: ' '
  notify: restart hsflowd
