- include_vars: "{{ ansible_distribution }}.yml"
  when: hsflow_download_url is undefined

- name: Download/Install hsflow for Ubuntu
  apt:
    deb: "{{ hsflow_download_url }}"
  when: ansible_distribution == "Ubuntu"

- name: Install hsflowd package for CentOS
  yum:
    name: "{{ hsflow_download_url }}"
    state: present
  when: ansible_distribution == "CentOS"

- set_fact:
    net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"

- name: Template config
  template:
    src: "hsflowd.conf.j2"
    dest: /etc/hsflowd.conf
  notify: restart hsflowd

- name: Enable hsflowd at boot
  service:
    name: hsflowd
    enabled: yes
