- name: Download/Install hsflow for Ubuntu
  apt:
    deb: "https://github.com/sflow/host-sflow/releases/download/v{{ hsflow_version }}/hsflowd-{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}_{{ hsflow_version }}_amd64.deb"
  when: ansible_distribution == "Ubuntu"

- name: Install hsflowd package for CentOS
  yum:
    name: "https://github.com/sflow/host-sflow/releases/download/v{{ hsflow_version }}/hsflowd-{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}-{{ hsflow_version }}.x86_64.rpm"
    state: present
  when: ansible_distribution == "CentOS"

- set_fact:
    net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"

- name: Template config fragments
  template:
    src: "hsflowd.conf.j2"
    dest: /etc/hsflowd.conf
  notify: restart hsflowd

- name: Enable hsflowd at boot
  service:
    name: hsflowd
    enabled: yes
