# Bummer, apt does not have the same interface as yum, thus two different tasks depending if
# installing from url or repo
- name: Download/Install hsflow for Ubuntu
  apt:
    deb: "{{ hsflow_download_url }}"
  when: ansible_distribution == "Ubuntu" and hsflow_web_install

- name: Install hsflowd package for Ubuntu
  apt:
    name: hsflowd
  when: ansible_distribution == "Ubuntu" and not hsflow_web_install

- name: Install hsflowd package for CentOS
  yum:
    name: "{{ hsflow_web_install | ternary( hsflow_download_url, 'hsflowd' ) }}"
    state: present
  when: ansible_distribution == "CentOS"

- set_fact:
    net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"

- name: Template config
  template:
    src: "hsflowd.conf.j2"
    dest: /etc/hsflowd.conf
  notify: restart hsflowd

- name: Enable hsflowd at boot
  service:
    name: hsflowd
    enabled: yes
