- name: Assert minimal hsflowd config if DNS-SD if disabled
  assert:
    that: hsflowd_collectors|length >= 1
    msg: "At least one collector must be defined."
  when: hsflowd_dnssd_disabled

- name: Install hsflowd with yum
  yum:
    name: "{{ hsflowd_url | default( hsflowd_package_name ) }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Install hsflowd with apt
  apt:
    deb: "{{ hsflowd_url is defined | ternary( hsflowd_url, omit ) }}"
    name: "{{ hsflowd_url is defined | ternary( omit, hsflowd_package_name ) }}"
  when: ansible_os_family is in ["Debian", "Cumulus Linux"]

- name: Template hsflowd.conf
  template:
    src: "hsflowd.conf.j2"
    dest: /etc/hsflowd.conf
  notify: restart hsflowd

- name: Enable/start hsflowd service
  service:
    name: hsflowd
    state: started
    enabled: yes
